//
// Created by zaida on 25.01.2024.
//

#ifndef IPFIXPROBE_CACHE_FLOWENDREASON_HPP
#define IPFIXPROBE_CACHE_FLOWENDREASON_HPP

namespace ipxp {
enum FlowEndReason:uint8_t {
    /*FLOW_END_INACTIVE,
    FLOW_END_ACTIVE,
    FLOW_END_NO_RES,
    FLOW_END_FORCED,
    FLOW_END_EOF,*/
    FLOW_END_INACTIVE_TIMEOUT,
    FLOW_END_ACTIVE_TIMEOUT,
    FLOW_END_TCP_EOF,
    FLOW_END_CACHE_SHUTDOWN,
    FLOW_END_POST_UPDATE,
    FLOW_END_PRE_UPDATE,
    FLOW_END_POST_CREATE,
    FLOW_END_NO_ROW_SPACE
};

} // namespace ipxp

#endif // IPFIXPROBE_CACHE_FLOWENDREASON_HPP
